(function (global) {
  const SSAT_WORD_BANK = [
    { word: "abundant", definition: "existing in large quantities", synonym: "plentiful" },
    { word: "adapt", definition: "to adjust to new conditions", synonym: "adjust" },
    { word: "adept", definition: "highly skilled", synonym: "skillful" },
    { word: "adversary", definition: "an opponent or enemy", synonym: "opponent" },
    { word: "agile", definition: "able to move quickly and easily", synonym: "nimble" },
    { word: "allure", definition: "the power to attract", synonym: "appeal" },
    { word: "amiable", definition: "friendly and pleasant", synonym: "friendly" },
    { word: "amplify", definition: "to make larger or stronger", synonym: "enlarge" },
    { word: "analyze", definition: "to examine carefully", synonym: "examine" },
    { word: "ancient", definition: "very old", synonym: "old" },
    { word: "antagonize", definition: "to make hostile", synonym: "provoke" },
    { word: "apparent", definition: "clearly visible or understood", synonym: "obvious" },
    { word: "ardent", definition: "very enthusiastic", synonym: "passionate" },
    { word: "arid", definition: "extremely dry", synonym: "dry" },
    { word: "articulate", definition: "able to express ideas clearly", synonym: "eloquent" },
    { word: "aspire", definition: "to seek to attain", synonym: "strive" },
    { word: "assert", definition: "to state confidently", synonym: "declare" },
    { word: "astute", definition: "having keen judgment", synonym: "shrewd" },
    { word: "audacious", definition: "bold and daring", synonym: "bold" },
    { word: "austere", definition: "severe or strict in manner", synonym: "stern" },
    { word: "authentic", definition: "genuine or real", synonym: "genuine" },
    { word: "banter", definition: "playful teasing", synonym: "joking" },
    { word: "benevolent", definition: "kind and generous", synonym: "kind" },
    { word: "brisk", definition: "quick and energetic", synonym: "lively" },
    { word: "candid", definition: "truthful and straightforward", synonym: "frank" },
    { word: "capable", definition: "having ability", synonym: "competent" },
    { word: "chaotic", definition: "in complete disorder", synonym: "disorderly" },
    { word: "coherent", definition: "logical and consistent", synonym: "logical" },
    { word: "compel", definition: "to force someone", synonym: "force" },
    { word: "comprehensive", definition: "including all or nearly all", synonym: "thorough" },
    { word: "conceal", definition: "to hide", synonym: "hide" },
    { word: "concur", definition: "to agree", synonym: "agree" },
    { word: "conspicuous", definition: "easily seen", synonym: "noticeable" },
    { word: "construct", definition: "to build", synonym: "build" },
    { word: "contemplate", definition: "to think deeply", synonym: "ponder" },
    { word: "conventional", definition: "based on tradition", synonym: "traditional" },
    { word: "convivial", definition: "friendly and cheerful", synonym: "sociable" },
    { word: "corroborate", definition: "to confirm with evidence", synonym: "confirm" },
    { word: "credible", definition: "believable", synonym: "believable" },
    { word: "cumulative", definition: "increasing by additions", synonym: "increasing" },
    { word: "daunt", definition: "to intimidate", synonym: "discourage" },
    { word: "deplete", definition: "to use up", synonym: "exhaust" },
    { word: "derive", definition: "to obtain from a source", synonym: "obtain" },
    { word: "deter", definition: "to discourage from acting", synonym: "discourage" },
    { word: "diligent", definition: "careful and hardworking", synonym: "industrious" },
    { word: "discern", definition: "to perceive clearly", synonym: "detect" },
    { word: "disclose", definition: "to reveal", synonym: "reveal" },
    { word: "dispute", definition: "to argue about", synonym: "argue" },
    { word: "diverse", definition: "showing variety", synonym: "varied" },
    { word: "dormant", definition: "inactive for a period", synonym: "inactive" },
    { word: "dynamic", definition: "energetic and changing", synonym: "energetic" },
    { word: "elaborate", definition: "detailed and complex", synonym: "detailed" },
    { word: "elated", definition: "very happy", synonym: "joyful" },
    { word: "elusive", definition: "hard to find or catch", synonym: "evasive" },
    { word: "emerge", definition: "to come out", synonym: "appear" },
    { word: "eminent", definition: "famous and respected", synonym: "distinguished" },
    { word: "endure", definition: "to last or suffer through", synonym: "withstand" },
    { word: "enhance", definition: "to improve", synonym: "improve" },
    { word: "enigmatic", definition: "mysterious", synonym: "mysterious" },
    { word: "entire", definition: "whole, complete", synonym: "complete" },
    { word: "eradicate", definition: "to destroy completely", synonym: "eliminate" },
    { word: "essential", definition: "absolutely necessary", synonym: "necessary" },
    { word: "evade", definition: "to avoid or escape", synonym: "avoid" },
    { word: "evident", definition: "plainly seen", synonym: "clear" },
    { word: "exceed", definition: "to go beyond", synonym: "surpass" },
    { word: "exceptional", definition: "unusually good", synonym: "remarkable" },
    { word: "exclude", definition: "to leave out", synonym: "omit" },
    { word: "expand", definition: "to increase in size", synonym: "broaden" },
    { word: "expedite", definition: "to speed up", synonym: "accelerate" },
    { word: "explicit", definition: "clear and exact", synonym: "specific" },
    { word: "feasible", definition: "possible to do", synonym: "practical" },
    { word: "fluctuate", definition: "to change irregularly", synonym: "vary" },
    { word: "formidable", definition: "inspiring fear or respect", synonym: "intimidating" },
    { word: "frugal", definition: "careful with money", synonym: "thrifty" },
    { word: "fundamental", definition: "basic and essential", synonym: "basic" },
    { word: "genuine", definition: "real, not fake", synonym: "authentic" },
    { word: "gradual", definition: "happening slowly", synonym: "slow" },
    { word: "gregarious", definition: "sociable", synonym: "outgoing" },
    { word: "hamper", definition: "to hinder", synonym: "obstruct" },
    { word: "hostile", definition: "unfriendly", synonym: "antagonistic" },
    { word: "hypothesis", definition: "a proposed explanation", synonym: "theory" },
    { word: "illuminate", definition: "to light up or clarify", synonym: "clarify" },
    { word: "impartial", definition: "fair, not biased", synonym: "neutral" },
    { word: "imply", definition: "to suggest without saying directly", synonym: "suggest" },
    { word: "incentive", definition: "something that motivates", synonym: "motivation" },
    { word: "incline", definition: "to lean toward", synonym: "tend" },
    { word: "indifferent", definition: "showing no interest", synonym: "unconcerned" },
    { word: "induce", definition: "to persuade or cause", synonym: "persuade" },
    { word: "inevitable", definition: "certain to happen", synonym: "unavoidable" },
    { word: "infer", definition: "to conclude from evidence", synonym: "deduce" },
    { word: "ingenious", definition: "clever and inventive", synonym: "innovative" },
    { word: "inhibit", definition: "to restrain", synonym: "restrict" },
    { word: "insight", definition: "deep understanding", synonym: "understanding" },
    { word: "integrity", definition: "honesty and moral principles", synonym: "honesty" },
    { word: "intense", definition: "extreme in degree", synonym: "extreme" },
    { word: "interact", definition: "to communicate with", synonym: "engage" },
    { word: "intricate", definition: "complex and detailed", synonym: "complicated" },
    { word: "justify", definition: "to show to be right", synonym: "defend" },
    { word: "keen", definition: "eager or sharp", synonym: "eager" },
    { word: "lament", definition: "to mourn", synonym: "grieve" },
    { word: "lucid", definition: "clear and easy to understand", synonym: "clear" },
    { word: "magnify", definition: "to make larger", synonym: "enlarge" },
    { word: "meticulous", definition: "very careful and precise", synonym: "careful" },
    { word: "modify", definition: "to change slightly", synonym: "adjust" },
    { word: "novel", definition: "new and unusual", synonym: "original" },
    { word: "obscure", definition: "not clear or well known", synonym: "unclear" },
    { word: "obtain", definition: "to get", synonym: "acquire" },
    { word: "omit", definition: "to leave out", synonym: "exclude" },
    { word: "optimistic", definition: "expecting good outcomes", synonym: "hopeful" },
    { word: "perceive", definition: "to become aware of", synonym: "notice" },
    { word: "persistent", definition: "continuing firmly", synonym: "tenacious" },
    { word: "plausible", definition: "seemingly reasonable", synonym: "credible" },
    { word: "precise", definition: "exact", synonym: "exact" },
    { word: "preclude", definition: "to prevent", synonym: "prevent" },
    { word: "predict", definition: "to say in advance", synonym: "forecast" },
    { word: "prevalent", definition: "widespread", synonym: "common" },
    { word: "profound", definition: "very deep or intense", synonym: "deep" },
    { word: "prominent", definition: "important and well known", synonym: "notable" },
    { word: "prudent", definition: "wise and careful", synonym: "wise" },
    { word: "random", definition: "without a pattern", synonym: "unpredictable" },
    { word: "rational", definition: "based on reason", synonym: "logical" },
    { word: "rebuke", definition: "to criticize sharply", synonym: "scold" },
    { word: "relevant", definition: "closely connected to topic", synonym: "pertinent" },
    { word: "reluctant", definition: "unwilling", synonym: "hesitant" },
    { word: "remorse", definition: "deep regret", synonym: "regret" },
    { word: "resilient", definition: "able to recover quickly", synonym: "tough" },
    { word: "resolve", definition: "to settle a problem", synonym: "solve" },
    { word: "rigid", definition: "stiff and inflexible", synonym: "stiff" },
    { word: "robust", definition: "strong and healthy", synonym: "strong" },
    { word: "scarce", definition: "in short supply", synonym: "rare" },
    { word: "scrutinize", definition: "to inspect closely", synonym: "inspect" },
    { word: "significant", definition: "important", synonym: "meaningful" },
    { word: "sincere", definition: "genuine and honest", synonym: "honest" },
    { word: "skeptical", definition: "doubting", synonym: "doubtful" },
    { word: "sporadic", definition: "occurring irregularly", synonym: "occasional" },
    { word: "stable", definition: "firm and not likely to change", synonym: "steady" },
    { word: "substantial", definition: "large in amount", synonym: "considerable" },
    { word: "sufficient", definition: "enough", synonym: "adequate" },
    { word: "superficial", definition: "on the surface only", synonym: "shallow" },
    { word: "sustain", definition: "to support or maintain", synonym: "maintain" },
    { word: "tenacious", definition: "holding firmly", synonym: "persistent" },
    { word: "tentative", definition: "not certain or fixed", synonym: "uncertain" },
    { word: "thrive", definition: "to grow well", synonym: "flourish" },
    { word: "tranquil", definition: "calm and peaceful", synonym: "calm" },
    { word: "ubiquitous", definition: "present everywhere", synonym: "widespread" },
    { word: "ultimate", definition: "final or best", synonym: "final" },
    { word: "unify", definition: "to join into one", synonym: "combine" },
    { word: "validate", definition: "to confirm as true", synonym: "verify" },
    { word: "venerable", definition: "worthy of respect due to age", synonym: "respected" },
    { word: "versatile", definition: "able to do many things", synonym: "adaptable" },
    { word: "vigilant", definition: "watchful", synonym: "alert" },
    { word: "vivid", definition: "very clear and detailed", synonym: "bright" },
    { word: "withstand", definition: "to resist successfully", synonym: "endure" },
    { word: "yield", definition: "to produce or give way", synonym: "produce" }
  ];

  function getWordBank() {
    return SSAT_WORD_BANK.map((item) => ({ ...item }));
  }
  const api = { getWordBank };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  global.SSATVocabData = api;
})(typeof window !== "undefined" ? window : globalThis);
