(function (global) {
  const FLASHCARD_CORE = [
    { word: "abate", definition: "to become less intense", synonym: "subside", antonym: "intensify", usage: "The storm began to abate before sunset." },
    { word: "abundant", definition: "existing in large quantities", synonym: "plentiful", antonym: "scarce", usage: "Fresh water is abundant in this region." },
    { word: "adept", definition: "very skilled", synonym: "proficient", antonym: "clumsy", usage: "She is adept at mental math." },
    { word: "adversary", definition: "an opponent", synonym: "rival", antonym: "ally", usage: "He respected his adversary in debate." },
    { word: "alleviate", definition: "to make easier to bear", synonym: "relieve", antonym: "worsen", usage: "A short break can alleviate stress." },
    { word: "amiable", definition: "friendly and pleasant", synonym: "affable", antonym: "hostile", usage: "Our new coach is amiable and patient." },
    { word: "analyze", definition: "to examine methodically", synonym: "examine", antonym: "ignore", usage: "Scientists analyze data before conclusions." },
    { word: "anomaly", definition: "something that differs from expected", synonym: "irregularity", antonym: "normality", usage: "The score jump was an anomaly." },
    { word: "apathy", definition: "lack of interest", synonym: "indifference", antonym: "enthusiasm", usage: "Apathy in class can hurt progress." },
    { word: "ardent", definition: "very enthusiastic", synonym: "passionate", antonym: "apathetic", usage: "She is an ardent reader." },
    { word: "articulate", definition: "to express clearly", synonym: "eloquent", antonym: "incoherent", usage: "He could articulate his strategy well." },
    { word: "audacious", definition: "bold and daring", synonym: "bold", antonym: "timid", usage: "It was an audacious plan." },
    { word: "benevolent", definition: "kind and generous", synonym: "kindhearted", antonym: "malevolent", usage: "The benevolent donor funded books." },
    { word: "candid", definition: "honest and direct", synonym: "frank", antonym: "deceitful", usage: "Please give candid feedback." },
    { word: "coherent", definition: "logical and clear", synonym: "consistent", antonym: "confused", usage: "Her explanation was coherent." },
    { word: "comprehensive", definition: "thorough; covering much", synonym: "extensive", antonym: "limited", usage: "We made a comprehensive review sheet." },
    { word: "concur", definition: "to agree", synonym: "agree", antonym: "disagree", usage: "I concur with your conclusion." },
    { word: "conspicuous", definition: "easy to notice", synonym: "noticeable", antonym: "inconspicuous", usage: "The typo was conspicuous." },
    { word: "credible", definition: "believable", synonym: "plausible", antonym: "doubtful", usage: "Her excuse sounded credible." },
    { word: "deplete", definition: "to use up", synonym: "exhaust", antonym: "replenish", usage: "Long droughts deplete reservoirs." },
    { word: "deter", definition: "to discourage", synonym: "discourage", antonym: "encourage", usage: "Clear rules deter cheating." },
    { word: "diligent", definition: "hardworking and careful", synonym: "industrious", antonym: "lazy", usage: "A diligent student practices daily." },
    { word: "disclose", definition: "to reveal", synonym: "reveal", antonym: "conceal", usage: "Do not disclose private data." },
    { word: "elated", definition: "extremely happy", synonym: "overjoyed", antonym: "dejected", usage: "The team felt elated after winning." },
    { word: "elusive", definition: "difficult to find or grasp", synonym: "evasive", antonym: "obvious", usage: "The answer was elusive at first." },
    { word: "eminent", definition: "famous and respected", synonym: "distinguished", antonym: "obscure", usage: "An eminent scientist visited campus." },
    { word: "enhance", definition: "to improve", synonym: "boost", antonym: "diminish", usage: "Practice can enhance fluency." },
    { word: "explicit", definition: "stated clearly", synonym: "specific", antonym: "vague", usage: "The teacher gave explicit directions." },
    { word: "frugal", definition: "careful with resources", synonym: "thrifty", antonym: "wasteful", usage: "Frugal habits help save money." },
    { word: "gregarious", definition: "sociable", synonym: "outgoing", antonym: "reserved", usage: "He is gregarious at group events." },
    { word: "hamper", definition: "to hinder", synonym: "obstruct", antonym: "assist", usage: "Noise can hamper concentration." },
    { word: "impartial", definition: "fair; unbiased", synonym: "neutral", antonym: "biased", usage: "A judge must remain impartial." },
    { word: "incentive", definition: "something that motivates", synonym: "motivation", antonym: "deterrent", usage: "Bonus points are an incentive." },
    { word: "inevitable", definition: "certain to happen", synonym: "unavoidable", antonym: "avoidable", usage: "Some mistakes are inevitable when learning." },
    { word: "ingenious", definition: "clever and inventive", synonym: "innovative", antonym: "unimaginative", usage: "That was an ingenious shortcut." },
    { word: "inhibit", definition: "to restrain", synonym: "restrict", antonym: "encourage", usage: "Fear can inhibit performance." },
    { word: "lucid", definition: "clear and easy to understand", synonym: "clear", antonym: "confusing", usage: "The article was lucid and concise." },
    { word: "meticulous", definition: "very careful with detail", synonym: "precise", antonym: "careless", usage: "Her notes are meticulous." },
    { word: "novel", definition: "new and original", synonym: "innovative", antonym: "conventional", usage: "They proposed a novel design." },
    { word: "obscure", definition: "not clear or well known", synonym: "unclear", antonym: "clear", usage: "The reference seemed obscure." },
    { word: "optimistic", definition: "expecting good outcomes", synonym: "hopeful", antonym: "pessimistic", usage: "Stay optimistic before the exam." },
    { word: "persistent", definition: "continuing despite difficulty", synonym: "tenacious", antonym: "inconsistent", usage: "Persistent effort builds skill." },
    { word: "plausible", definition: "seemingly reasonable", synonym: "believable", antonym: "implausible", usage: "Your theory sounds plausible." },
    { word: "precise", definition: "exact and accurate", synonym: "exact", antonym: "inexact", usage: "Use precise language in writing." },
    { word: "prevalent", definition: "common and widespread", synonym: "common", antonym: "rare", usage: "Smartphones are prevalent now." },
    { word: "profound", definition: "deep and meaningful", synonym: "deep", antonym: "superficial", usage: "The speech had a profound effect." },
    { word: "prudent", definition: "wise and cautious", synonym: "wise", antonym: "reckless", usage: "It is prudent to double-check." },
    { word: "rational", definition: "based on reason", synonym: "logical", antonym: "irrational", usage: "Make a rational decision." },
    { word: "relevant", definition: "directly related", synonym: "pertinent", antonym: "irrelevant", usage: "Give only relevant evidence." },
    { word: "reluctant", definition: "unwilling", synonym: "hesitant", antonym: "eager", usage: "He was reluctant to speak first." },
    { word: "resilient", definition: "quick to recover", synonym: "tough", antonym: "fragile", usage: "Resilient learners bounce back." },
    { word: "robust", definition: "strong and healthy", synonym: "strong", antonym: "weak", usage: "We need robust evidence." },
    { word: "scrutinize", definition: "to inspect carefully", synonym: "examine", antonym: "overlook", usage: "Scrutinize each answer choice." },
    { word: "skeptical", definition: "doubtful", synonym: "doubtful", antonym: "convinced", usage: "She remained skeptical of rumors." },
    { word: "sporadic", definition: "occurring irregularly", synonym: "occasional", antonym: "frequent", usage: "Attendance was sporadic." },
    { word: "substantial", definition: "large in amount", synonym: "considerable", antonym: "insignificant", usage: "They made substantial progress." },
    { word: "superficial", definition: "only on the surface", synonym: "shallow", antonym: "profound", usage: "A superficial reading misses nuance." },
    { word: "tenacious", definition: "not giving up", synonym: "persistent", antonym: "yielding", usage: "She is tenacious in practice." },
    { word: "tentative", definition: "uncertain", synonym: "uncertain", antonym: "definite", usage: "We made a tentative schedule." },
    { word: "tranquil", definition: "calm and peaceful", synonym: "calm", antonym: "agitated", usage: "The library felt tranquil." },
    { word: "ubiquitous", definition: "present everywhere", synonym: "widespread", antonym: "rare", usage: "Screens are ubiquitous in daily life." },
    { word: "vigilant", definition: "watchful and alert", synonym: "alert", antonym: "careless", usage: "Stay vigilant during lab work." },
    { word: "vivid", definition: "bright and clear", synonym: "striking", antonym: "dull", usage: "The story gave vivid images." }
  ];

  const api = {
    getDeck() {
      return FLASHCARD_CORE.map((w) => ({ ...w }));
    },
  };

  if (typeof module !== "undefined" && module.exports) module.exports = api;
  global.SSATFlashcardDeck = api;
})(typeof window !== "undefined" ? window : globalThis);
